/-
Copyright (c) 2026 Ara Aslyan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ara Aslyan
-/
import HAomega.HsSemantics

/-!
# Haskell emission for HA^ω terms

This backend prints an already-extracted `HAomega.Tm` as Haskell source.  It is
therefore simpler than `Realizability.Meta.EmitHaskell`: the proof has already
been translated into a closed System T term by `extractClosed`, and this file
only renders that term.

Scope: this is a string generator, not a certified compiler.  Lean checks that
the source generator is total; GHC is the checker for the generated source.
-/

namespace HAomega.EmitHaskell

/-- Haskell type corresponding to an HA^ω finite type. -/
def hsTy : Ty → String
  | .unit => "()"
  | .ord => "Eps0"
  | .hyd => "Hydra"
  | .nat => "Integer"
  | .arrow a b => "(" ++ hsTy a ++ " -> " ++ hsTy b ++ ")"
  | .prod a b => "(" ++ hsTy a ++ ", " ++ hsTy b ++ ")"

/-- **Render an HA^ω term as a Haskell expression.**

Since the certified-semantics work this is *defined* as printing the verified
translation: `hsOf` is the map proved correct in `HsSemantics.lean`
(`hsOf_correct`), and `hsPrint` renders its output.  So the string shipped in
`EXTRACTED_HAOMEGA.md` is produced from the AST the theorem is about, by
construction — there is no second, unverified walk over `Tm` any more.

What remains outside the theorem is exactly the printing and GHC's parsing of
the result, plus the prelude below implementing the primitives. -/
def hsTm {Γ : List Ty} {τ : Ty} (t : Tm Γ τ) (d : Nat) : String :=
  hsPrint (hsOf t) d

/-- Runtime support for emitted System T terms.

`oltN` and `tiRec` are included so every `Tm` constructor has a printed target,
but they are intentionally partial placeholders here.  Fibonacci and Pascal do
not use them. -/
def hsPrelude : String :=
"-- GENERATED by HAomega/EmitHaskell.lean -- NOT a certified artifact.

natRec :: a -> (Integer -> a -> a) -> Integer -> a
natRec z _ 0 = z
natRec z s n
  | n > 0 = s (n - 1) (natRec z s (n - 1))
  | otherwise = z

oltN :: Integer -> Integer -> Integer
oltN = error \"HAomega.EmitHaskell: port Realizability.oltN for epsilon-zero programs\"

tiRec :: (Integer -> (Integer -> () -> a) -> a) -> Integer -> a
tiRec = error \"HAomega.EmitHaskell: Haskell backend has no certified epsilon-zero recursion\"
"

/-- A complete Haskell module defining one closed HA^ω term. -/
def moduleFor {τ : Ty} (modName fnName : String) (t : Tm [] τ) : String :=
  "module " ++ modName ++ " where\n\n" ++
  hsPrelude ++ "\n" ++
  fnName ++ " :: " ++ hsTy τ ++ "\n" ++
  fnName ++ " = " ++ hsTm t 0 ++ "\n"

end HAomega.EmitHaskell
