/-
Copyright (c) 2026 Ara Aslyan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ara Aslyan
-/
import HAomega.Syntax

/-!
# Haskell emission for HA^ω terms

This backend prints an already-extracted `HAomega.Tm` as Haskell source.  It is
therefore simpler than `Realizability.Meta.EmitHaskell`: the proof has already
been translated into a closed System T term by `extractClosed`, and this file
only renders that term.

Scope: this is a string generator, not a certified compiler.  Lean checks that
the source generator is total; GHC is the checker for the generated source.
-/

namespace HAomega.EmitHaskell

/-- Haskell type corresponding to an HA^ω finite type. -/
def hsTy : Ty → String
  | .unit => "()"
  | .ord => "Eps0"
  | .hyd => "Hydra"
  | .nat => "Integer"
  | .arrow a b => "(" ++ hsTy a ++ " -> " ++ hsTy b ++ ")"
  | .prod a b => "(" ++ hsTy a ++ ", " ++ hsTy b ++ ")"

/-- Render a variable as the de Bruijn *level* used by the surrounding lambdas. -/
def hsVar : {Γ : List Ty} → {τ : Ty} → Var Γ τ → Nat → String
  | _, _, .here, d => "x" ++ toString (d - 1)
  | _, _, .there v, d => hsVar v (d - 1)

/-- Recognise numerals, so `S (S 0)` prints as `2`. -/
partial def numLit? : {Γ : List Ty} → Tm Γ .nat → Option Nat
  | _, .zero => some 0
  | _, .succ t => (numLit? t).map (· + 1)
  | _, _ => none

/-- Render an HA^ω term as a Haskell expression. -/
partial def hsTm : {Γ : List Ty} → {τ : Ty} → Tm Γ τ → Nat → String
  | _, _, .var v, d => hsVar v d
  | _, _, .lam t, d => "(\\x" ++ toString d ++ " -> " ++ hsTm t (d + 1) ++ ")"
  | _, _, .app f a, d => "(" ++ hsTm f d ++ " " ++ hsTm a d ++ ")"
  | _, _, .star, _ => "()"
  | _, _, .pair a b, d => "(" ++ hsTm a d ++ ", " ++ hsTm b d ++ ")"
  | _, _, .fst t, d => "(fst " ++ hsTm t d ++ ")"
  | _, _, .snd t, d => "(snd " ++ hsTm t d ++ ")"
  | _, _, .zero, _ => "0"
  | _, _, .succ t, d =>
      match numLit? (.succ t) with
      | some n => toString n
      | none => "(1 + " ++ hsTm t d ++ ")"
  | _, _, .add a b, d => "(" ++ hsTm a d ++ " + " ++ hsTm b d ++ ")"
  | _, _, .recNat z s n, d => "(natRec " ++ hsTm z d ++ " " ++ hsTm s d ++ " " ++ hsTm n d ++ ")"
  | _, _, .prec a b, d => "(oltN " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .pred a, d => "(predN " ++ hsTm a d ++ ")"
  | _, _, .bump a b, d => "(bumpN " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .good a b, d => "(goodN " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .ord a b, d => "(ordOfN " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .hcut a b, d => "(hydraStepN " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .hcutAt p a b, d =>
      "(playAtN " ++ hsTm p d ++ " " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .ezero, _ => "EZero"
  | _, _, .orde a b, d => "(ordE " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .olte a b, d => "(oltNE " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .tiRecE s n, d => "(tiRecE " ++ hsTm s d ++ " " ++ hsTm n d ++ ")"
  | _, _, .hleaf, _ => "hLeaf"
  | _, _, .hcutH a b, d => "(hydraStep " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .hleafQ a, d => "(isLeafN " ++ hsTm a d ++ ")"
  | _, _, .hordH a, d => "(ordEOfHydra " ++ hsTm a d ++ ")"
  | _, _, .hydra a b, d => "(hydraSeqN " ++ hsTm a d ++ " " ++ hsTm b d ++ ")"
  | _, _, .hord a, d => "(ordOfHydraN " ++ hsTm a d ++ ")"
  | _, _, .tiRec s n, d => "(tiRec " ++ hsTm s d ++ " " ++ hsTm n d ++ ")"

/-- Runtime support for emitted System T terms.

`oltN` and `tiRec` are included so every `Tm` constructor has a printed target,
but they are intentionally partial placeholders here.  Fibonacci and Pascal do
not use them. -/
def hsPrelude : String :=
"-- GENERATED by HAomega/EmitHaskell.lean -- NOT a certified artifact.

natRec :: a -> (Integer -> a -> a) -> Integer -> a
natRec z _ 0 = z
natRec z s n
  | n > 0 = s (n - 1) (natRec z s (n - 1))
  | otherwise = z

oltN :: Integer -> Integer -> Integer
oltN = error \"HAomega.EmitHaskell: port Realizability.oltN for epsilon-zero programs\"

tiRec :: (Integer -> (Integer -> () -> a) -> a) -> Integer -> a
tiRec = error \"HAomega.EmitHaskell: Haskell backend has no certified epsilon-zero recursion\"
"

/-- A complete Haskell module defining one closed HA^ω term. -/
def moduleFor {τ : Ty} (modName fnName : String) (t : Tm [] τ) : String :=
  "module " ++ modName ++ " where\n\n" ++
  hsPrelude ++ "\n" ++
  fnName ++ " :: " ++ hsTy τ ++ "\n" ++
  fnName ++ " = " ++ hsTm t 0 ++ "\n"

end HAomega.EmitHaskell
