-- ============================================================================
-- Extracted Haskell Module from Lean 4 / HA^omega Constructive ODE Solver
-- Generated by HAomega.EmitHaskell & HAomega.ODEExtraction
-- ============================================================================

module Main where

import Data.Ratio

-- ----------------------------------------------------------------------------
-- 1. Standard HA^omega System T Runtime Support (from HAomega.EmitHaskell)
-- ----------------------------------------------------------------------------

-- System T Primitive Recursor on Naturals (recNat)
natRec :: a -> (Integer -> a -> a) -> Integer -> a
natRec z _ 0 = z
natRec z s n
  | n > 0 = s (n - 1) (natRec z s (n - 1))
  | otherwise = z

-- ----------------------------------------------------------------------------
-- 2. The Exact Extracted Closed Picard Functional from HAomega.ODEExtraction
--    System T Term: \y0 -> \t -> \n -> recNat y0 (\i acc -> t acc) n
-- ----------------------------------------------------------------------------

odePicardIter :: a -> (a -> a) -> Integer -> a
odePicardIter y0 t n = natRec y0 (\_ acc -> t acc) n

-- ----------------------------------------------------------------------------
-- 3. Exact Rational Polynomial Integration in Haskell
-- ----------------------------------------------------------------------------

type Poly = [Rational]

-- Polynomial Integration: \int_0^x P(t) dt = \sum \frac{c_j}{j+1} x^{j+1}
polyIntegrate :: Poly -> Poly
polyIntegrate p = 0 : zipWith (\j c -> c / fromIntegral (j + 1)) [0..] p

-- Polynomial Evaluation at Rational x: P(x)
evalPoly :: Poly -> Rational -> Rational
evalPoly p x = sum $ zipWith (\j c -> c * (x ^ j)) [0..] p

-- ----------------------------------------------------------------------------
-- 4. Instantiation A: Solving y' = y, y(0) = 1 (Exponential Growth)
--    Picard Operator: T(P)(x) = 1 + \int_0^x P(t) dt
-- ----------------------------------------------------------------------------

expPicardStep :: Poly -> Poly
expPicardStep p = 1 : tail (polyIntegrate p)

-- Solution synthesized via extracted odePicardIter:
expSolution :: Integer -> Poly
expSolution n = odePicardIter [1] expPicardStep n

-- ----------------------------------------------------------------------------
-- 5. Instantiation B: Solving y'' + y = 0 (Harmonic Oscillator)
--    Simultaneous 2D Picard Operator for (sin, cos):
--    T(P1, P2) = ( \int_0^x P2(t) dt , 1 - \int_0^x P1(t) dt )
-- ----------------------------------------------------------------------------

type State2D = (Poly, Poly)

harmonicPicardStep :: State2D -> State2D
harmonicPicardStep (p1, p2) =
  let p1_next = polyIntegrate p2
      p2_next = 1 : map negate (tail (polyIntegrate p1))
  in (p1_next, p2_next)

-- 2D Solution synthesized via extracted odePicardIter:
harmonicSolution :: Integer -> State2D
harmonicSolution n = odePicardIter ([0], [1]) harmonicPicardStep n

-- ----------------------------------------------------------------------------
-- 6. Main Runner Demonstrating Kernel-Verified Execution in Haskell
-- ----------------------------------------------------------------------------

main :: IO ()
main = do
  putStrLn "========================================================================"
  putStrLn "  Constructive ODE Solver Extracted from HA^omega / Lean 4 (GHC Runner)"
  putStrLn "========================================================================"
  putStrLn ""
  putStrLn "--- 1. Exponential y' = y, y(0) = 1 evaluated at x = 1/2 ---"
  let x = 1 % 2
  mapM_ (\n -> do
    let p = expSolution n
    let val = evalPoly p x
    putStrLn $ "  Iterate P_" ++ show n ++ "(1/2) = " ++ show (numerator val) ++ "/" ++ show (denominator val)
            ++ " ≈ " ++ show (fromRational val :: Double)
    ) [0..6]

  putStrLn ""
  putStrLn "--- 2. Harmonic Oscillator y'' + y = 0 evaluated at x = 1/2 ---"
  mapM_ (\n -> do
    let (pSin, pCos) = harmonicSolution n
    let valSin = evalPoly pSin x
    let valCos = evalPoly pCos x
    putStrLn $ "  Iterate N=" ++ show n ++ ":"
    putStrLn $ "    sin(1/2) ≈ " ++ show (numerator valSin) ++ "/" ++ show (denominator valSin)
            ++ " ≈ " ++ show (fromRational valSin :: Double)
    putStrLn $ "    cos(1/2) ≈ " ++ show (numerator valCos) ++ "/" ++ show (denominator valCos)
            ++ " ≈ " ++ show (fromRational valCos :: Double)
    ) [0..5]
  putStrLn ""
  putStrLn "========================================================================"
  putStrLn "  Successfully executed extracted System T program in Haskell!"
  putStrLn "========================================================================"
